modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "brightbronze_horizons"
version = "${version}"
displayName = "Brightbronze Horizons"
authors = "Gaius"
description = '''
A chunk-expansion mod where players expand their playable area by spawning terrain chunks from biome-coherent source dimensions.
'''

[[dependencies.brightbronze_horizons]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brightbronze_horizons]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brightbronze_horizons]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "brightbronze_horizons.mixins.json"
