modLoader = "javafml"
loaderVersion = "[10,)"
license = "MIT"

[[mods]]
modId = "brightbronze_horizons"
version = "${version}"
displayName = "Brightbronze Horizons"
authors = "Gaius"
description = '''
A chunk-expansion mod where players expand their playable area by spawning terrain chunks from biome-coherent source dimensions.
'''

[[dependencies.brightbronze_horizons]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brightbronze_horizons]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brightbronze_horizons]]
modId = "architectury"
type = "required"
versionRange = "[18.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "brightbronze_horizons.mixins.json"

[[mixins]]
config = "brightbronze_horizons_12110.mixins.json"
